# Lazygit popup
bind g display-popup -d "#{pane_current_path}" -w 100% -h 100% -E "lazygit"

# C-hjkl navigation for TUI editors
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?|hx)(diff)?$'"

bind-key -n C-h if-shell "$is_vim" "send-keys C-h" 
bind-key -n C-j if-shell "$is_vim" "send-keys C-j" 
bind-key -n C-k if-shell "$is_vim" "send-keys C-k" 
bind-key -n C-l if-shell "$is_vim" "send-keys C-l" 

# tmux session name
set -g status-left-length 40
set -g status-left "[#S] "

# tmux command palette
bind p display-popup -d "#{pane_current_path}" -E -w 40% -h 90% "bash $HOME/.local/bin/tmux-cmd-palette"

